- task: NuGetCommand@2
  displayName: 'Push to MyArtifactsFeed'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'StringUtilitiesCI/MyArtifactsFeed'